# Generated by Django 5.2.7 on 2025-11-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_alter_customuser_options_cart_order_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=10, verbose_name='Баланс'),
        ),
    ]
